[package]
name = "dsc"
version = "0.1.0"
authors = ["Jeremy Schwartz <j.schwartz564@icloud.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
smallvec = "1.4"

[dev-dependencies]
proptest = "0.10"
